#!/bin/bash

url() {
query=""
for this_query_term in $@
do
  query="${query}${this_query_term}"
done
url="http://${query}"
  open "$url"
}

google() {
query=""
for this_query_term in $@
do
  query="${query}${this_query_term}+"
done
url="http://www.google.com/search?q=${query}"
  open "$url"
}

wiki() {
query=""
for this_query_term in $@
do
  query="${query}${this_query_term}+"
done
url="https://en.wikipedia.org/wiki/Special:Search?search=${query}"
  open "$url"
}

youtube() {
query=""
for this_query_term in $@
do
  query="${query}${this_query_term}+"
done
url="http://www.youtube.com/results?search_query=${query}"
  open "$url"
}

$1 $2 $3 $4
